// <auto-generated />
using System;
using KyberKlass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KyberKlass.Data.Migrations
{
    [DbContext(typeof(KyberKlassDbContext))]
    [Migration("20260528145612_AddFullSeedData")]
    partial class AddFullSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KyberKlass.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("DATE");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e321fa43-9c90-4e01-8f0a-002eae899e98"),
                            AccessFailedCount = 0,
                            Address = "1416 Ryan Mountains",
                            BirthDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "d4f6406d-9b51-4290-994d-cf1bb9668b5e",
                            Email = "admin@kyberklass.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@KYBERKLASS.COM",
                            NormalizedUserName = "ADMIN@KYBERKLASS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC5tNYhoMOyMvOrciUf9NiZXU+KjuRqcsUpSfjzBFVcxs4dbf/VuygK600x/tUpYVQ==",
                            PhoneNumber = "08888888888",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("420abb62-30a5-4983-835e-fe0a46b6f463"),
                            SecurityStamp = "0DB9D047-3375-4739-9C32-217CC8337032",
                            TwoFactorEnabled = false,
                            UserName = "admin@kyberklass.com"
                        },
                        new
                        {
                            Id = new Guid("427a6f9a-bee1-4493-9d13-65ab478bb5f5"),
                            AccessFailedCount = 0,
                            Address = "15 Teacher Lane",
                            BirthDate = new DateTime(1999, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "0f9d3f0d-9f65-4f72-9a3f-3f95cb98f8f1",
                            Email = "teacher@kyberklass.com",
                            EmailConfirmed = false,
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER@KYBERKLASS.COM",
                            NormalizedUserName = "TEACHER@KYBERKLASS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBMhCEHC1SlQhTUbcVXS+qy1gIGblfslsv9YtBPjZjBmWFpv2r+m1gQ7eifAWnQmsg==",
                            PhoneNumber = "0881111111",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("3f262f2b-bd05-4b24-9a6c-bca365d372fb"),
                            SecurityStamp = "A1B2C3D4-E5F6-7890-ABCD-EF1234567890",
                            TwoFactorEnabled = false,
                            UserName = "teacher@kyberklass.com"
                        },
                        new
                        {
                            Id = new Guid("9dae1d79-f917-4acd-bc32-b78408e702a3"),
                            AccessFailedCount = 0,
                            Address = "16 Teacher Blvd",
                            BirthDate = new DateTime(1998, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "2c6e4b80-1b6a-4f1d-a83d-4bfbda34f4c7",
                            Email = "teacher2@kyberklass.com",
                            EmailConfirmed = false,
                            FirstName = "Leon",
                            IsActive = true,
                            LastName = "Leblanc",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER2@KYBERKLASS.COM",
                            NormalizedUserName = "TEACHER2@KYBERKLASS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEBW0XfusVI/5/B9vVQUeyJ1znh3TzHdMaJYEGuAhEPLGS0tHN/nmsd/Xl4RwyuGsA==",
                            PhoneNumber = "0882222222",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("3f262f2b-bd05-4b24-9a6c-bca365d372fb"),
                            SecurityStamp = "B2C3D4E5-F6A7-8901-BCDE-F12345678901",
                            TwoFactorEnabled = false,
                            UserName = "teacher2@kyberklass.com"
                        },
                        new
                        {
                            Id = new Guid("db0dc8be-db06-4b53-a0e3-1a5cb3fa40da"),
                            AccessFailedCount = 0,
                            Address = "4445 Smithfield Avenue",
                            BirthDate = new DateTime(2002, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "d4f6406d-9b51-4290-994d-cf1bb9668b5e",
                            Email = "guardian@kyberklass.com",
                            EmailConfirmed = false,
                            FirstName = "Belle",
                            IsActive = true,
                            LastName = "Moon",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUARDIAN@KYBERKLASS.COM",
                            NormalizedUserName = "GUARDIAN@KYBERKLASS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHYICPBp9IFFJqFmVQJHIB4siaTffkQp8qDPSH0Y56+C9fBswnIyq4XMxtG/KA8K/w==",
                            PhoneNumber = "08844444444",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("74efc216-b31e-4ed3-96d0-7dc2296eec3b"),
                            SecurityStamp = "0DB9D047-3375-4739-9C32-217CC8337032",
                            TwoFactorEnabled = false,
                            UserName = "guardian@kyberklass.com"
                        },
                        new
                        {
                            Id = new Guid("b0aab2ce-41d6-4a7e-b9d4-0b2c7ced288a"),
                            AccessFailedCount = 0,
                            Address = "4445 Smithfield Avenue",
                            BirthDate = new DateTime(2010, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "4f8c1d7a-9b22-4d66-a5e1-2c7f9b0d3e55",
                            Email = "student@kyberklass.com",
                            EmailConfirmed = false,
                            FirstName = "Neo",
                            IsActive = true,
                            LastName = "Joyce",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@KYBERKLASS.COM",
                            NormalizedUserName = "STUDENT@KYBERKLASS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPVO2VHn1sUvzMAWmdmsv5Q3TFcqhuQUs7VWkALHyG6ODp1VEripi+tOEJhhsaxybw==",
                            PhoneNumber = "0881234567",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("f697e34c-843e-467a-b11f-037e185c180f"),
                            SecurityStamp = "A7D2F941-5C88-4E19-B3D0-6F2A8C7E1B44",
                            TwoFactorEnabled = false,
                            UserName = "student@kyberklass.com"
                        },
                        new
                        {
                            Id = new Guid("58d10548-8f58-48ba-9eff-73e0d87bf7b9"),
                            AccessFailedCount = 0,
                            Address = "4445 Smithfield Avenue",
                            BirthDate = new DateTime(2011, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "b7d2e4f9-1c88-4a10-93f6-7e2c5d1a9b33",
                            Email = "student2@kyberklass.com",
                            EmailConfirmed = false,
                            FirstName = "Crystal",
                            IsActive = true,
                            LastName = "Lane",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT2@KYBERKLASS.COM",
                            NormalizedUserName = "STUDENT2@KYBERKLASS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEATrWWc4wiAkLGWlHp+hz/Afyw/vl7ykXjDoVQgic0wJFIjvRS4ERbnpLHehJRIi5A==",
                            PhoneNumber = "0887654321",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("f697e34c-843e-467a-b11f-037e185c180f"),
                            SecurityStamp = "3E9B1C57-8A44-42F0-9D61-5C7A2E8F0B19",
                            TwoFactorEnabled = false,
                            UserName = "student2@kyberklass.com"
                        });
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b9a4da2-8b83-4e71-ab43-916663ca9ca4"),
                            IsActive = true,
                            Name = "A",
                            SchoolId = new Guid("6cead59f-b8d4-4528-bd6d-e0e5dc97eaee"),
                            TeacherId = new Guid("427a6f9a-bee1-4493-9d13-65ab478bb5f5")
                        },
                        new
                        {
                            Id = new Guid("63e35421-bd57-4de6-940d-e239c1886ad5"),
                            IsActive = true,
                            Name = "B",
                            SchoolId = new Guid("08ed558b-d9ee-4663-b2b7-e700fd3620e6"),
                            TeacherId = new Guid("9dae1d79-f917-4acd-bc32-b78408e702a3")
                        });
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Guardians");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db0dc8be-db06-4b53-a0e3-1a5cb3fa40da")
                        });
                });

            modelBuilder.Entity("KyberKlass.Data.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cead59f-b8d4-4528-bd6d-e0e5dc97eaee"),
                            Address = "Promishlena zona Hladilnika, bul. \"Nikola Y. Vaptsarov\" 47, 1407 Sofia",
                            Email = "st@example.com",
                            IsActive = true,
                            Name = "St. George International School",
                            PhoneNumber = "02 414 4414"
                        },
                        new
                        {
                            Id = new Guid("08ed558b-d9ee-4663-b2b7-e700fd3620e6"),
                            Address = "Sofia Center, Pozitano St 26, 1000 Sofia",
                            Email = "schoolb@ez.com",
                            IsActive = true,
                            Name = "91. Немска езикова гимназия „Проф. Константин Гълъбов“",
                            PhoneNumber = "02 987 5305"
                        },
                        new
                        {
                            Id = new Guid("1e633a7a-7d6c-413a-b8bf-3081324cee7e"),
                            Address = "Rnd. Address",
                            Email = "test_schoolc@ez.com",
                            IsActive = true,
                            Name = "Test School",
                            PhoneNumber = "02 987 0000"
                        });
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("GuardianId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0aab2ce-41d6-4a7e-b9d4-0b2c7ced288a"),
                            ClassroomId = new Guid("3b9a4da2-8b83-4e71-ab43-916663ca9ca4"),
                            GuardianId = new Guid("db0dc8be-db06-4b53-a0e3-1a5cb3fa40da"),
                            SchoolId = new Guid("6cead59f-b8d4-4528-bd6d-e0e5dc97eaee")
                        },
                        new
                        {
                            Id = new Guid("58d10548-8f58-48ba-9eff-73e0d87bf7b9"),
                            ClassroomId = new Guid("63e35421-bd57-4de6-940d-e239c1886ad5"),
                            GuardianId = new Guid("db0dc8be-db06-4b53-a0e3-1a5cb3fa40da"),
                            SchoolId = new Guid("08ed558b-d9ee-4663-b2b7-e700fd3620e6")
                        });
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("427a6f9a-bee1-4493-9d13-65ab478bb5f5")
                        },
                        new
                        {
                            Id = new Guid("9dae1d79-f917-4acd-bc32-b78408e702a3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("420abb62-30a5-4983-835e-fe0a46b6f463"),
                            ConcurrencyStamp = "dc7b742e-e5e3-4537-af41-32803244d217",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("3f262f2b-bd05-4b24-9a6c-bca365d372fb"),
                            ConcurrencyStamp = "c6d865bf-6f64-4d47-b49f-6866b58619b7",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = new Guid("f697e34c-843e-467a-b11f-037e185c180f"),
                            ConcurrencyStamp = "6cf6c247-d253-4793-a753-cb2eb090b234",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = new Guid("74efc216-b31e-4ed3-96d0-7dc2296eec3b"),
                            ConcurrencyStamp = "8e906f0e-342d-46de-8249-118201686478",
                            Name = "Guardian",
                            NormalizedName = "GUARDIAN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e321fa43-9c90-4e01-8f0a-002eae899e98"),
                            RoleId = new Guid("420abb62-30a5-4983-835e-fe0a46b6f463")
                        },
                        new
                        {
                            UserId = new Guid("427a6f9a-bee1-4493-9d13-65ab478bb5f5"),
                            RoleId = new Guid("3f262f2b-bd05-4b24-9a6c-bca365d372fb")
                        },
                        new
                        {
                            UserId = new Guid("9dae1d79-f917-4acd-bc32-b78408e702a3"),
                            RoleId = new Guid("3f262f2b-bd05-4b24-9a6c-bca365d372fb")
                        },
                        new
                        {
                            UserId = new Guid("db0dc8be-db06-4b53-a0e3-1a5cb3fa40da"),
                            RoleId = new Guid("74efc216-b31e-4ed3-96d0-7dc2296eec3b")
                        },
                        new
                        {
                            UserId = new Guid("b0aab2ce-41d6-4a7e-b9d4-0b2c7ced288a"),
                            RoleId = new Guid("f697e34c-843e-467a-b11f-037e185c180f")
                        },
                        new
                        {
                            UserId = new Guid("58d10548-8f58-48ba-9eff-73e0d87bf7b9"),
                            RoleId = new Guid("f697e34c-843e-467a-b11f-037e185c180f")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KyberKlass.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Classroom", b =>
                {
                    b.HasOne("KyberKlass.Data.Models.School", "School")
                        .WithMany("Classrooms")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KyberKlass.Data.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Guardian", b =>
                {
                    b.HasOne("KyberKlass.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Student", b =>
                {
                    b.HasOne("KyberKlass.Data.Models.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KyberKlass.Data.Models.Guardian", "Guardian")
                        .WithMany("Students")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KyberKlass.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KyberKlass.Data.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Classroom");

                    b.Navigation("Guardian");

                    b.Navigation("School");
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Teacher", b =>
                {
                    b.HasOne("KyberKlass.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KyberKlass.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KyberKlass.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KyberKlass.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KyberKlass.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("KyberKlass.Data.Models.Guardian", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("KyberKlass.Data.Models.School", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
